pub const LUNA_INSTALLER_DEVICE_FIRMWARE_READ_DIAG_OFFSET: usize = 0xC0001;
pub const LUNA_INSTALLER_DEVICE_FIRMWARE_READ_DIAG_SIZE: usize = 1;
pub const LUNA_INSTALLER_DEVICE_AHCI_ABAR_OFFSET: usize = 0xC66A0;
pub const LUNA_INSTALLER_DEVICE_AHCI_ABAR_SIZE: usize = 8;
pub const LUNA_INSTALLER_DEVICE_AHCI_PORT_OFFSET: usize = 0xC66A8;
pub const LUNA_INSTALLER_DEVICE_AHCI_PORT_SIZE: usize = 1;
pub const LUNA_INSTALLER_DEVICE_AHCI_READY_OFFSET: usize = 0xC66A9;
pub const LUNA_INSTALLER_DEVICE_AHCI_READY_SIZE: usize = 1;
